### ISSUE TITLE
Getting Form to Run in Tekla

### ISSUE THREAD

**Issue by BKSpurgeon** [teklanology/Tekla-Form-Macro#1]
Hi Dale

Thank you for your template.

I want to get it working/running from Tekla - the form that is.

I don't really know how to do this.

Any explanations would be much appreciated.

rgds

Ben

**Comment by dalenicholls** [comment]
apologies for not replying sooner, i wasn't watching the repo.
you should be able to just drop it in the modeling/drawing macro directory.
you can do some other stuff too that will help which i'll blog about soon...

**Comment by BKSpurgeon** [comment]
ok chrs Dale, looking fwd to your posts.

rgds

Ben

**Comment by dalenicholls** [comment]
By default Class Library should be selected.
![image](https://user-images.githubusercontent.com/725255/33596564-08891f7a-d994-11e7-8212-3d3436f9883c.png)

Then it's a matter copying the .cs/.dll file to the XS_MACRO_DIRECTORY that can be automated using the Build Events > Post-build event command line.

Then you can run the macro from the Tools > Macros list.

![image](https://user-images.githubusercontent.com/725255/33596573-12c3cada-d994-11e7-8537-1f4445f2f417.png)

### Bonus Round...
Using the code below, you can get your program to report to a file instead of using Console.WriteLine("...")

`string path = @"C:\log.log";`
`TextWriterTraceListener textWriterTraceListener = new TextWriterTraceListener(File.CreateText(path));`
`Debug.Listeners.Add(textWriterTraceListener);`
`Trace.AutoFlush = true;`
`Trace.WriteLine("log initialised...");`

I also recommend [Reattach](https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach). By attaching visual studio to TeklaStructures, the code above then outputs to the Output panel.
